import { Case, DetectiveCharacter, LabItem, LabCombination } from "./types";

export const DEMO_TOPIC = "🕵️‍♂️ Murder Mystery";
export const DEMO_INVESTIGATION_TITLE = "The Gilded Ghost Case";

export const DEMO_CHARACTER: DetectiveCharacter = {
  name: "Inspector Voss",
  personality: "Methodical and sharp-eyed with decades of experience",
  tone: "Calm, precise, analytical",
  expertise: "Forensic Reasoning & Pattern Analysis",
  gender: "male",
};

export const DEMO_CASES: Case[] = [
  {
    case_id: 1,
    status: "unlocked",
    title: "The Final Toast",
    scenario: "Billionaire Arthur Sterling was found dead in his study after a private gala. A single glass of vintage scotch sat on his desk, still half-full. The security footage shows him entering alone, but his personal physician, Dr. Aris, was the last person to leave the wing before the gala ended.",
    character_dialogue: "Poisoning... a coward's weapon, but effective. Look at the residue in that glass. Normal scotch doesn't leave a crystalline precipitate at room temperature. What was Arthur Sterling actually drinking?",
    evidence: {
      type: "image",
      description: "A close-up of a crystal scotch glass. A faint, white powdery ring is visible around the liquid's edge. A discarded capsule blister pack was found in the wastebin nearby, labeled 'Digitalis_3.5mg'. A silver serving tray nearby has a faint fingerprint marked 'ST_9901'.",
      generation_prompt: "Macro photograph of a vintage crystal glass with amber liquid, a white powdery ring on the rim, dark mahogany desk background, forensic evidence markers, dramatic shadows",
      hidden_clue: "Digitalis is a heart medication that, in high doses, causes fatal cardiac arrest—leaving exactly this type of residue.",
    },
    terminal_code: "9901",
    question: "What substance was used to poison Arthur Sterling, and what evidence confirms it?",
    expected_answer: "digitalis",
    acceptable_variations: ["digitalis", "poisoned with heart medication", "digitalis powder", "digitalis capsule"],
    hint: "Check the wastebin evidence. What's the name on that capsule pack?",
    explanation: "The victim was poisoned with a lethal dose of Digitalis, a heart medication. The white ring on the glass edge is the un-dissolved crystalline residue of the crushed capsules.",
    difficulty: "Beginner",
    lab_items: [
      { id: "glass", label: "Glass Residue", icon: "🥃", type: "text" },
      { id: "capsule", label: "Capsule Pack", icon: "💊", type: "text" },
      { id: "fingerprint", label: "Fingerprint ST_9901", icon: "🔍", type: "text" },
      { id: "toxreport", label: "Toxicology Report", icon: "🧪", type: "text" },
      { id: "visual", label: "Visual Scan", icon: "📸", type: "image" },
    ],
    lab_combinations: [
      { items: ["glass", "capsule"], prompt: "Forensic microscope view of white crystalline Digitalis powder residue dissolving in amber scotch liquid, laboratory glass slide, high magnification", clue: "The crystalline residue on the glass matches crushed Digitalis capsules — a lethal cardiac poison." },
      { items: ["glass", "fingerprint"], prompt: "UV-lit fingerprint analysis on a crystal scotch glass rim, forensic dusting powder glowing, dark lab background", clue: "The fingerprint ST_9901 on the glass belongs to the serving staff — someone else handled this glass after Sterling." },
      { items: ["glass", "toxreport"], prompt: "Medical toxicology report document showing elevated Digitalis glycoside levels in blood sample, clinical chart, forensic lighting", clue: "Blood toxicology confirms lethal concentrations of Digitalis glycosides — 8x the therapeutic dose." },
      { items: ["capsule", "fingerprint"], prompt: "Forensic evidence bag containing a blister pack of pills with a dusted fingerprint highlighted under UV light, evidence table", clue: "The fingerprint on the capsule blister pack does NOT match the victim — someone planted it." },
      { items: ["capsule", "toxreport"], prompt: "Side-by-side comparison of a Digitalis 3.5mg capsule and a chemical analysis readout showing matching molecular structure, lab bench", clue: "The capsule dosage of 3.5mg x 6 capsules = 21mg total. The lethal dose is 10mg. This was deliberate." },
      { items: ["fingerprint", "toxreport"], prompt: "Detective case board showing a timeline connecting fingerprint evidence to medical records, red string connections, cork board", clue: "Dr. Aris prescribed Digitalis to Sterling last month. The fingerprint ST_9901 matches Aris's medical assistant." },
      { items: ["visual", "glass"], prompt: "Digital forensic enhancement of a scotch glass rim showing a microscopic white powdery ring, computer UI overlay, scanning lines", clue: "The visual scan reveals the powder was applied to the rim *before* the drink was poured." },
      { items: ["visual", "capsule"], prompt: "Close up of a Digitalis blister pack showing one capsule missing and a residue of identical white powder on the foil, macro photography", clue: "The powder residue on the packaging foil is visually identical to the ring on the glass." },
    ],
    lab_hint: "Try performing a Visual Scan on the Glass or the Capsule to look for microscopic residue patterns.",
    terminal_video_prompt: "Security footage of a suspect's hand subtly swapping a glass on a table, grainy 90s aesthetic, timestamps in corner",
    terminal_audio_text: "The trace analysis confirms the presence of Digitalis. The concentration suggests it was added directly to the container before consumption.",
  },
  {
    case_id: 2,
    status: "locked",
    title: "The Entangled Alibi",
    scenario: "Two physicists claim they were in separate labs 50 kilometers apart. However, their quantum communication logs show perfectly correlated measurement results. The security system confirms both labs' doors were accessed at the claimed times.",
    character_dialogue: "Entangled photons maintain correlation regardless of distance. But look at the timing of their measurements in this surveillance clip. Bell's theorem tells us something interesting about the measurement choices...",
    evidence: {
      type: "video",
      description: "Security footage showing measurement basis choices being logged. Lab A and Lab B show identical basis switches from Z to X at the exact same microsecond, 847 times in a row. A system watermark in the corner reads: 'LOG_INIT_1997'.",
      generation_prompt: "Close up video of digital clocks in two separate laboratory monitors ticking in perfect synchronicity, scientific data scrolling, high tech forensic atmosphere",
      hidden_clue: "Simultaneous basis switching 847 times is astronomically unlikely unless pre-coordinated.",
    },
    terminal_code: "1997",
    question: "What does the measurement data reveal about the scientists' claims?",
    expected_answer: "coordinated",
    acceptable_variations: ["pre-coordinated", "measurement choices were planned", "basis switching was coordinated", "they shared a measurement schedule"],
    hint: "In quantum experiments, the measurement basis choice should be random. What does it mean when two independent labs make identical choices 847 times in a row?",
    explanation: "While quantum entanglement produces correlated results, the *choice* of measurement basis should be random. Identical choices 847 times proves coordination.",
    difficulty: "Intermediate",
    lab_items: [
      { id: "logdata", label: "Measurement Logs", icon: "📊", type: "text" },
      { id: "timing", label: "Timing Analysis", icon: "⏱️", type: "text" },
      { id: "security", label: "Door Access Logs", icon: "🚪", type: "text" },
      { id: "belltest", label: "Bell Test Results", icon: "🔔", type: "text" },
      { id: "visual", label: "Visual Scan", icon: "📸", type: "image" },
    ],
    lab_combinations: [
      { items: ["logdata", "timing"], prompt: "Split screen of two laboratory monitors showing identical data switching patterns at the exact same microsecond, digital forensic overlay, green terminal text", clue: "847 identical basis switches at the same microsecond — the probability of this being random is essentially zero." },
      { items: ["logdata", "security"], prompt: "Security access log printout next to a laboratory data log, timestamps highlighted with red circles showing correlation, forensic desk", clue: "Both labs were accessed 30 minutes before the official experiment start — enough time to synchronize equipment." },
      { items: ["logdata", "belltest"], prompt: "Scientific graph showing Bell inequality violation test results with suspicious perfectly straight correlation line, academic paper style", clue: "A true Bell test would show statistical noise. This data is too clean — it was pre-computed, not measured." },
      { items: ["timing", "security"], prompt: "Timeline infographic showing door access events and measurement events on parallel tracks, connected by dotted red lines, dark background", clue: "The measurement basis choices were locked in BEFORE the entangled particles were even generated." },
      { items: ["timing", "belltest"], prompt: "Computer screen showing a failed Bell inequality test with annotations pointing to timing loopholes, hacker terminal aesthetic", clue: "The timing data reveals a 12ms gap — enough for a classical signal to travel between labs at light speed." },
      { items: ["security", "belltest"], prompt: "Surveillance camera still showing a USB drive being inserted into lab equipment, timestamp visible, grainy security footage style", clue: "Security footage shows a USB drive was used to load pre-computed measurement sequences into both labs' equipment." },
      { items: ["visual", "logdata"], prompt: "Computer screen showing a comparison of two quantum state plots with a highlighted 'impossible' overlap, neon blue and green colors", clue: "Visual analysis of the logs shows the quantum states were cloned — a physical impossibility without a shared source." },
      { items: ["visual", "security"], prompt: "Thermal camera footage of a hand pressing a keypad, heat signatures of the numbers 1, 9, 8, 4 glowing on the buttons", clue: "Thermal scan of the keypad reveals the code 1984 was used just minutes before the detection." },
    ],
    lab_hint: "Connect the Security Footage and Log Data to see if the door events match the quantum state anomalies.",
    terminal_video_prompt: "Computer monitor showing a split screen comparison of two identical biometric login sequences from different labs, glowing green text",
    terminal_audio_text: "Initial door logs show both physicists entered their labs at exactly 14:00:00. However, the quantum heartbeat suggests they were accessing a shared server.",
  },
  {
    case_id: 3,
    status: "locked",
    title: "The Observer's Paradox",
    scenario: "CERN experiments produced results that violated the no-communication theorem. A whistleblower suggests the experimental apparatus itself may be the source of the anomaly.",
    character_dialogue: "If the results seem to break physics, the instrument is lying, not the universe. Examine the detector calibration chain end-to-end.",
    evidence: {
      type: "image",
      description: "A technical signal path diagram. It reveals that detectors at both ends share a common clock synchronization signal through a single fiber optic cable with a 3.7-nanosecond uncorrected delay. The protocol version is marked 'OS_2042'.",
      generation_prompt: "Detailed scientific signal path diagram on a blueprint, fiber optic lines highlighted, technical annotations, 3.7ns delay marked in red",
      hidden_clue: "The shared clock synchronization creates a hidden variable that produces apparent superluminal correlation.",
    },
    terminal_code: "2042",
    question: "Why did the experiment appear to violate the no-communication theorem?",
    expected_answer: "delay",
    acceptable_variations: ["shared clock", "clock synchronization delay", "common clock signal", "systematic timing error", "3.7 nanosecond delay"],
    hint: "If they all got the same wrong result, the error must be in the shared apparatus. Look at what connects the two detectors.",
    explanation: "A 3.7-nanosecond propagation delay in the shared clock synchronization cable created artificial correlations that mimicked faster-than-light communication.",
    difficulty: "Expert",
    lab_items: [
      { id: "signal", label: "Signal Path Data", icon: "📡", type: "text" },
      { id: "fiber", label: "Fiber Optic Cable", icon: "🔌", type: "text" },
      { id: "clock", label: "Clock Sync Module", icon: "🕐", type: "text" },
      { id: "detector", label: "Detector Readings", icon: "📈", type: "text" },
      { id: "visual", label: "Visual Scan", icon: "📸", type: "image" },
    ],
    lab_combinations: [
      { items: ["signal", "fiber"], prompt: "Technical diagram of a fiber optic cable carrying both data signal and clock synchronization signal, cross-section view, engineering blueprint style", clue: "Both detectors share a SINGLE fiber optic cable for clock sync — creating a hidden common cause." },
      { items: ["signal", "clock"], prompt: "Oscilloscope display showing two waveforms with a 3.7 nanosecond phase offset, green phosphor screen, laboratory instrument", clue: "The clock synchronization signal has a 3.7ns propagation delay that was never corrected in calibration." },
      { items: ["signal", "detector"], prompt: "Split view of two particle detector readouts showing suspiciously correlated spikes, scientific monitoring interface, dark control room", clue: "The detector correlations disappear when you subtract the 3.7ns clock offset — it's a systematic artifact." },
      { items: ["fiber", "clock"], prompt: "Close-up of a fiber optic junction box with a highlighted delay measurement of 3.7 nanoseconds, technical macro photography", clue: "The fiber optic cable introduces exactly 3.7ns of delay — matching the anomalous correlation window perfectly." },
      { items: ["fiber", "detector"], prompt: "Schematic showing signal flow from fiber optic input through detector electronics with timing annotations, circuit diagram style", clue: "When the shared fiber is replaced with independent clocks, the superluminal correlations vanish entirely." },
      { items: ["clock", "detector"], prompt: "Before-and-after comparison graphs: correlated detector data with shared clock vs uncorrelated data with independent clocks, scientific publication figure", clue: "The no-communication violation is purely an artifact of shared timing infrastructure, not real physics." },
      { items: ["visual", "signal"], prompt: "Spectrum analyzer showing a hidden low-frequency signal buried inside the main data stream, complex waveform visualization", clue: "The visual spectrum scan shows a 'heartbeat' signal hidden in the noise — a side-channel used for sync." },
      { items: ["visual", "fiber"], prompt: "Microscopic cross-section of a fiber optic cable showing a tiny fracture that causes light to leak between channels, glowing fiber core", clue: "A microscopic crack in the fiber causes 'crosstalk' — letting one detector see the other's signal." },
    ],
    lab_hint: "Perform a Visual Scan on the Fiber Optic cable or the Signal Path Data to inspect for physical tampering or hidden 'heartbeat' signals.",
    terminal_video_prompt: "Macro video of light pulses traveling through a fiber optic cable, showing a subtle leakage of photons at a specific point, high speed camera",
    terminal_audio_text: "The crosstalk was intentional. A micro-fracture was used to sync the detectors, effectively creating a hidden channel between Lab A and Lab B.",
  },
];

/* ══════════ PHOTOSYNTHESIS DATA ══════════ */
export const PHOTOSYNTHESIS_TOPIC = "🌿 Photosynthesis";
export const PHOTOSYNTHESIS_INVESTIGATION_TITLE = "The Green Engine Protocol";
export const PHOTOSYNTHESIS_CHARACTER: DetectiveCharacter = {
  name: "Dr. Chlora",
  personality: "Ecologically minded forensic botanist",
  tone: "Calm, organic, insightful",
  expertise: "Bio-chemical Forensic Analysis",
  gender: "female",
};

export const PHOTOSYNTHESIS_CASES: Case[] = [
  {
    case_id: 1,
    status: "unlocked",
    title: "The Stifled Breath",
    scenario: "A rare greenhouse exhibit began wilting despite perfect hydration and light. Security sensors recorded a localized atmospheric anomaly around the leaves at midnight. The facility's carbon scrubbing system was found to be operating at 150% capacity during the event.",
    character_dialogue: "Plants breathe through microscopic pores. If the scrubbing system sucked all the available CO2 out of the air, the Calvin cycle would grind to a halt. What is the name of these tiny breathing pores?",
    evidence: {
      type: "image",
      description: "A microscopic view of a leaf's underside. The tiny oval pores are completely tightly shut. A digital log on the side shows the greenhouse humidity spiked in the year 2018. A faint residue of calcium carbonate is visible near the leaf veins.",
      generation_prompt: "Scanning electron microscope image of leaf stomata, high magnification, pores closed tightly, organic green textures, scientific annotations, forensic lighting",
      hidden_clue: "The pores are closed to prevent water loss, but in this case, they were forced shut by the lack of ambient CO2.",
    },
    terminal_code: "2018",
    question: "What is the name of the leaf pores that were found closed?",
    expected_answer: "stomata",
    acceptable_variations: ["stoma", "stomates", "pores"],
    hint: "Think about the microscopic openings on the underside of a leaf used for gas exchange.",
    explanation: "The stomata closed due to the lack of CO2, preventing the dark reactions of photosynthesis from occurring.",
    difficulty: "Beginner",
    lab_items: [
      { id: "peel", label: "Leaf Peel", icon: "🍃", type: "text" },
      { id: "co2_log", label: "CO2 Sensor Log", icon: "📉", type: "text" },
      { id: "calcium", label: "Mineral Residue", icon: "⚪", type: "text" },
      { id: "scrubber", label: "Scrubber Status", icon: "⚙️", type: "text" },
      { id: "visual", label: "Visual Scan", icon: "📸", type: "image" },
    ],
    lab_combinations: [
      { items: ["peel", "co2_log"], prompt: "Forensic graph showing leaf pore diameter vs CO2 concentration, scientific data visualization", clue: "The stomata closed exactly when the CO2 levels dropped below 50ppm." },
      { items: ["peel", "visual"], prompt: "Magnified view of a leaf stoma with a red 'CLOSED' indicator overlay, digital forensic UI", clue: "Visual scan confirms 100% closure of all observed stomatal apertures." },
      { items: ["co2_log", "scrubber"], prompt: "Infographic showing the correlation between air scrubber power and CO2 depletion, tech drawing", clue: "The scrubber was intentionally set to 'Vacuum' mode to starve the plants." },
      { items: ["peel", "calcium"], prompt: "Microscopic view of calcium deposits clogging a leaf pore, forensic botany", clue: "Calcium carbonate was sprayed to physically block any remaining gas exchange." },
      { items: ["co2_log", "visual"], prompt: "Thermal map of a greenhouse showing cold zones where CO2 was being sucked out, overhead view", clue: "The CO2 depletion was localized specifically to the 'Rare Exhibits' sector." },
      { items: ["scrubber", "visual"], prompt: "Internal view of a mechanical air filter showing human fingerprints in dust, forensic dusting", clue: "The scrubber settings were manually overridden at 11:45 PM." },
    ],
    lab_hint: "Connect the Leaf Peel to the CO2 Log to see how the plant responded to the air quality changes.",
    terminal_video_prompt: "Time-lapse video of a plant's stomata closing under high-intensity forensic lighting, microscopic view",
    terminal_audio_text: "The atmospheric scrubbers were manipulated. By removing the carbon dioxide, the suspect effectively suffocated the plant from the inside out.",
  },
  {
    case_id: 2,
    status: "locked",
    title: "The Violet Sabotage",
    scenario: "An experimental crop was failing despite being under constant high-intensity grow lights. The plants appear healthy but are not producing any glucose. Spectrometric analysis suggests a filter was placed over the primary light source.",
    character_dialogue: "Chlorophyll doesn't absorb all light equally. It loves red and blue, but it reflects green. If someone filtered out the blue and red wavelengths, the plant would be 'blind' even in bright light. What is the primary pigment responsible for this?",
    evidence: {
      type: "video",
      description: "Security footage of a light technician swapping out a bulb. The new bulb emits a strange, yellowish-green hue. A sticker on the bulb casing reads 'REF_1962'. A light spectrum readout shows a massive dip in the 430nm and 660nm ranges.",
      generation_prompt: "Video of a laboratory spectrometer screen showing a light intensity graph with huge gaps in the red and blue regions, flickering monitor aesthetic",
      hidden_clue: "The 430nm and 660nm peaks are the primary absorption ranges for Chlorophyll a.",
    },
    terminal_code: "1962",
    question: "What is the primary pigment that was unable to absorb the filtered light?",
    expected_answer: "chlorophyll",
    acceptable_variations: ["chlorophyll-a", "chlorophyll-b", "pigment"],
    hint: "It's the green pigment found in chloroplasts.",
    explanation: "The sabotage involved filtering out the red and blue wavelengths, which chlorophyll requires to power the light-dependent reactions.",
    difficulty: "Intermediate",
    lab_items: [
      { id: "spectro", label: "Spectrometer Data", icon: "🌈", type: "text" },
      { id: "extract", label: "Pigment Extract", icon: "🧪", type: "text" },
      { id: "bulb", label: "Light Bulb", icon: "💡", type: "text" },
      { id: "growth", label: "Growth Chart", icon: "📈", type: "text" },
      { id: "visual", label: "Visual Scan", icon: "📸", type: "image" },
    ],
    lab_combinations: [
      { items: ["spectro", "extract"], prompt: "Comparison of a standard absorption spectrum vs the sabotaged light source, scientific chart", clue: "The sabotaged light completely misses the chlorophyll absorption peaks." },
      { items: ["extract", "visual"], prompt: "Microscopic view of chloroplasts under a green filter, looking dark and inactive, forensic botany", clue: "Under the sabotaged light, the chlorophyll remains in a 'ground state' — no energy is being captured." },
      { items: ["bulb", "spectro"], prompt: "Technical analysis of a light bulb glass showing a chemical coating that filters blue light, macro view", clue: "The bulb was coated with a thin layer of chromium-green dye to block the 430nm wavelength." },
      { items: ["bulb", "visual"], prompt: "UV light revealing a hidden fingerprint on the sabotaged light bulb, forensic lab", clue: "The fingerprint on the bulb belongs to the lead gardener's rival." },
      { items: ["extract", "growth"], prompt: "Graph showing zero starch production despite 24/7 lighting, laboratory report", clue: "Since no light is being absorbed, no ATP is produced, and no glucose is synthesized." },
      { items: ["spectro", "bulb"], prompt: "3D model of light rays passing through a filter and being blocked, scientific visualization", clue: "The filter was designed to specifically target the most efficient photosynthetic wavelengths." },
    ],
    lab_hint: "Combine the Spectrometer Data with the Pigment Extract to see which wavelengths were being ignored.",
    terminal_video_prompt: "Scientific animation of a photon hitting a chlorophyll molecule but being reflected instead of absorbed due to the wrong wavelength",
    terminal_audio_text: "The light was a lie. By bathing the plants in only green light, the saboteur ensured they couldn't capture a single watt of energy.",
  },
  {
    case_id: 3,
    status: "locked",
    title: "The Proton Leak",
    scenario: "A high-yield corn variant suddenly stopped producing energy. Molecular analysis shows that while water is being split and electrons are moving, no ATP is being generated. The thylakoid membranes appear to have lost their structural integrity.",
    character_dialogue: "To make ATP, you need a gradient — a crowded room of protons on one side of a membrane. If the wall has holes, the protons leak out, and the turbine stops spinning. What is the name of this 'turbine' enzyme?",
    evidence: {
      type: "image",
      description: "A high-resolution molecular scan of a chloroplast. Tiny 'holes' are visible in the thylakoid discs. A digital timestamp in the corner of the scan reads 'CAL_2025'. A chemical trace of 'Ionophore-B' is detected in the lipid bilayer.",
      generation_prompt: "Detailed 3D molecular visualization of a thylakoid membrane with glowing protons leaking through small gaps, scientific animation style",
      hidden_clue: "Ionophore-B makes membranes permeable to ions, destroying the electrochemical gradient.",
    },
    terminal_code: "2025",
    question: "What enzyme uses the proton gradient to produce ATP?",
    expected_answer: "synthase",
    acceptable_variations: ["atp-synthase", "atp-synthetase", "atpsynthase"],
    hint: "It's the complex that acts like a molecular motor to phosphorylate ADP.",
    explanation: "The chemical Ionophore-B made the thylakoid membranes leaky, preventing the formation of a proton gradient and stopping ATP synthase from functioning.",
    difficulty: "Expert",
    lab_items: [
      { id: "atp_assay", label: "ATP Assay", icon: "⚡", type: "text" },
      { id: "ion_trace", label: "Ionophore Trace", icon: "🧬", type: "text" },
      { id: "membrane", label: "Thylakoid Sample", icon: "🦠", type: "text" },
      { id: "gradient", label: "pH Gradient Map", icon: "🧪", type: "text" },
      { id: "visual", label: "Visual Scan", icon: "📸", type: "image" },
    ],
    lab_combinations: [
      { items: ["membrane", "gradient"], prompt: "Heat map of a thylakoid showing protons leaking out through the edges, molecular visualization", clue: "The pH gradient is nearly zero across the membrane — the 'battery' is flat." },
      { items: ["atp_assay", "membrane"], prompt: "A molecular motor (ATP synthase) sitting idle while protons flow past it without turning it, 3D render", clue: "ATP synthase is physically intact, but there's no pressure to turn it." },
      { items: ["ion_trace", "membrane"], prompt: "Ionophore molecules wedging themselves into a lipid bilayer creating a tunnel, molecular forensic view", clue: "Ionophore-B has created 'proton tunnels' that bypass the natural ATP production path." },
      { items: ["ion_trace", "atp_assay"], prompt: "Chemical reaction graph showing ATP production crashing as Ionophore concentration rises, lab report", clue: "The inhibition is non-competitive; the chemistry is fine, but the physics of the gradient is broken." },
      { items: ["membrane", "visual"], prompt: "Cross-section of a chloroplast showing swollen and ruptured thylakoid stacks, scanning electron micrograph", clue: "Visual scan shows structural 'ballooning' of the thylakoids due to osmotic imbalance." },
      { items: ["gradient", "visual"], prompt: "Fluorescent imaging of a leaf cell showing protons (bright dots) scattered randomly instead of concentrated, microscopic view", clue: "The cell is alive, but its energy production infrastructure has been 'short-circuited'." },
    ],
    lab_hint: "Use the Visual Scan on the Thylakoid Sample to see if you can spot the structural leaks.",
    terminal_video_prompt: "3D animation of ATP synthase spinning rapidly and then coming to a dead stop as protons begin to leak through the membrane",
    terminal_audio_text: "We found traces of a synthetic ionophore. It didn't kill the plant; it just unplugged the generator by letting the protons leak away.",
  },
];
